mysite/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_panel.urls')),
    path('', include('sale.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sale/urls.py
from django.urls import path
from sale.views import cash_orders, promocode_requests_accept, promocode_requests_reject, promocodes_create, sale_diller_delete, sale_diller_detail, sale_dillers_create, update_cash_order, sale_seller, update_sale_seller, wait_cashback, accept_cashback, reject_cashback, update_cashback, sale_statistics
from sale.views import promocodes, promocodes_create_xlsx, promocodes_edit, promocodes_delete
from sale.views import cars, cars_create, cars_edit, cars_delete, promocodes_check, give_to_diller
from sale.views import sale_seller_edit
from sale.views import (
    promocode_requests,
    promocode_requests_edit,
    # promocode_requests_accept,
    # promocode_requests_reject
)
from sale.views import (
    sale_seller2,
    sale_seller2_edit,
    update_sale_seller2
)

from sale.views import sale_dillers


urlpatterns = [
    path('cash/orders', cash_orders, name="cash_orders"),
    path('cash/orders/update/<int:pk>/<int:state>',
         update_cash_order, name="update_cash_orders"),
    path('sale/seller', sale_seller, name="sale_seller"),
    path('sale/seller/<int:pk>', sale_seller_edit, name="seller_edit"),
    path('sale/seller/update/<int:pk>/<int:state>',
         update_sale_seller, name="update_sale_seller"),


    path('cashback/wait', wait_cashback, name="wait_cashback"),
    path('cashback/accept', accept_cashback, name="accept_cashback"),
    path('cashback/reject', reject_cashback, name="reject_cashback"),
    path('cashback/update/<int:pk>/<int:state>',
         update_cashback, name="update_cashback"),

    path('sale/statistics/<int:pk>', sale_statistics, name="statistics"),



    path('promocodes/', promocodes, name="promocodes"),
    path('promocodes/<int:pk>', promocodes_edit, name="promocodes-edit"),
    path('promocodes/delete/<int:pk>',
         promocodes_delete, name="promocodes-delete"),
    path('promocodes/create', promocodes_create, name="promocode-create"),
    path('promocodes/create_xlsx', promocodes_create_xlsx,
         name="promocode-create-xlsx"),
    path('promocodes/check/<str:seria>',
         promocodes_check, name="promocode-check"),
    path('promocodes/give_to_diller', give_to_diller,
         name="promocode-give_to_diller"),



    path('cars/', cars, name="cars"),
    path('cars/<int:pk>', cars_edit, name="cars-edit"),
    path('cars/delete/<int:pk>', cars_delete, name="cars-delete"),
    path('cars/create', cars_create, name="cars-create"),




    path('cars/create', cars_create, name="cars-create"),




    path('promocode_requests/', promocode_requests, name="promocode-requests"),
    path('promocode_requests/<int:pk>', promocode_requests_edit,
         name="promocode-request-edit"),
    path('promocode_requests/<int:pk>', promocode_requests_edit,
         name="promocode-request-delete"),

    path('promocode_requests/accept', promocode_requests,
         name="promocode-request-accept"),
    path('promocode_requests/<int:pk>/accept',
         promocode_requests_accept, name="promocode-request-accept"),
    path('promocode_requests/<int:pk>/reject',
         promocode_requests_reject, name="promocode-request-reject"),





    path('sale_dillers/', sale_dillers, name="sale_dillers"),
    path('sale_dillers/create', sale_dillers_create, name="sale_dillers_create"),
    path('sale_dillers/<int:pk>/', sale_diller_detail, name="sale_diller_detail"),
    path('sale_dillers/<int:pk>/delete',
         sale_diller_delete, name="sale_diller_delete"),





    path('sale/seller2', sale_seller2, name="sale_seller2"),
    path('sale/seller2/<int:pk>', sale_seller2_edit, name="seller_edit2"),
    path('sale/seller2/update/<int:pk>/<int:state>',
         update_sale_seller2, name="update_sale_seller2"),


]

admin_panel/forms.py
from dataclasses import fields
from django import forms
from admin_panel.models import Category, District, Gifts,Product, Promotion, Regions,Text,BaseProduct
from diller.models import Diller



class CategoryForm(forms.ModelForm):
    class Meta:

        model = Category
        fields = '__all__'
        widgets = {
            'name_uz': forms.TextInput(attrs={
                'class': "form-control",
                
                }),
            'name_ru': forms.TextInput(attrs={
                'class': "form-control ",
                
                }),
        }

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'category': forms.TextInput(attrs={
                'class': "form-control ",
                
                }),
            'name_uz': forms.TextInput(attrs={
                'class': "form-control ",
                
                }),
            'name_ru': forms.TextInput(attrs={
                'class': "form-control ",
                
                }),
            'diller_ball': forms.NumberInput(attrs={
                'class': "form-control ",
                
                }),
            'diller_nasiya_ball': forms.NumberInput(attrs={
                'class': "form-control ",
                
                }),
            'seller_ball': forms.NumberInput(attrs={
                'class': "form-control ",
                
                }),
            'price': forms.NumberInput(attrs={
                'class': "form-control "
                
                }),
            'code': forms.TextInput(attrs={
                'class': "form-control "
                
                }),
            'last_code': forms.NumberInput(attrs={
                'class': "form-control "
                
                })
        }

class GiftsForm(forms.ModelForm):
    class Meta:

        model = Gifts
        fields = ["gift_type","name_uz","name_ru","ball","amount"]
        widgets = {
            'gift_type': forms.Select(attrs={
                'class': "form-control select2 select2-hidden-accessible",
                
                }),
            'name_uz': forms.TextInput(attrs={
                'class': "form-control ",
                
                }),
            'name_ru': forms.TextInput(attrs={
                'class': "form-control ",
                
                }),
            'ball': forms.NumberInput(attrs={
                'class': "form-control ",
                
                }),
            'amount': forms.NumberInput(attrs={
                'class': "form-control ",
                
                }),
        }

class RegionsForm(forms.ModelForm):
    class Meta:

        model = Regions
        fields = '__all__'
        widgets = {
            'uz_data': forms.TextInput(attrs={
                'class': "form-control ",
                
                }),
            'ru_data': forms.TextInput(attrs={
                'class': "form-control ",
                
                }),
        }


class DistrictForm(forms.ModelForm):
    class Meta:

        model = District
        fields = '__all__'
        widgets = {
            'uz_data': forms.TextInput(attrs={
                'class': "form-control ",
                
                }),
            'ru_data': forms.TextInput(attrs={
                'class': "form-control ",
                
                }),
        }

class TextForm(forms.ModelForm):
    class Meta:
        model = Text
        fields = ['uz_data','ru_data']
        widgets = {
            'uz_data': forms.TextInput(attrs={
                'class': "form-control",
                
                }),
            'ru_data': forms.TextInput(attrs={
                'class': "form-control",
                
                }),
        }
class SoldForm(forms.ModelForm):
    serial2 = forms.IntegerField()
    class Meta:
        print("Heloodfdsoo")
        model = BaseProduct
        fields = ['diller','product','seller']
        widgets = {
            'diller': forms.Select(attrs={
                'class': "form-control select2 select2-hidden-accessible",
                
                }),
            'seller': forms.Select(attrs={
                'class': "form-control select2 select2-hidden-accessible",
                
                }),
            'product': forms.Select(attrs={
                'class': "form-control select2 select2-hidden-accessible",
                
                }),
            'serial2': forms.TextInput(attrs={'class': "form-control "})
        }
class PromotionForm(forms.ModelForm):
    class Meta:
        model = Promotion
        fields = "__all__"
        widgets = {
            'product': forms.Select(attrs={
                'class': "form-control select2 select2-hidden-accessible"
                
                }),
            'price': forms.NumberInput(attrs={
                'class': "form-control "
                
                }),
            'ball': forms.NumberInput(attrs={
                'class': "form-control "
                
                }),
            'count': forms.NumberInput(attrs={
                'class': "form-control "
                
                }),
            'active': forms.CheckboxInput(attrs={
                'class': "" 
                
                }),
            'description_uz': forms.Textarea(attrs={
                'class': "form-control "
                
                }),
            'description_ru': forms.Textarea(attrs={
                'class': "form-control "
                
                })
        }


class DillerForm(forms.ModelForm):
    class Meta:
        model = Diller
        fields = ["name","number","region","district"]
        widgets = {
            'region': forms.Select(attrs={
                'class': "form-control select2 select2-hidden-accessible"
                
                }),
            'district': forms.Select(attrs={
                'class': "form-control select2 select2-hidden-accessible"
                
                }),
            'name': forms.TextInput(attrs={
                'class': "form-control "
                
                }),
            'number': forms.NumberInput(attrs={
                'class': "form-control "
                
                })
                   }

templates/dashboard/sold/diller_sold.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load currency %}
{% block content %}
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Сотилаганлар</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'home' %}">Асосий</a></li>
          <li class="breadcrumb-item active">Сотилаганлар</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title mr-2">Сотилаганлар</h3>
                <div class="card-tools d-flex">
                  <form class="d-flex form-horizontal" method="get">
                    <div>
                      <select class="form-control" name="filter_product" id="">
                        <option  value="all">Barchasi</option>
                        <option  value="day">Kunlik</option>
                        <option  value="month">Oylik</option>
                        <option  value="year">Yillik</option>
                      </select>
                    </div>
                    <div><button class="btn btn-info ml-2" type="submit">Filter</button></div>
                  </form>
                    <a class="mr-3" href="{% url 'solds' %}"><div class="btn btn-block btn-secondary ml-2">Ortga</div></a>
                </div>
              </div>

              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                  <thead>

                    <tr>
                      <th>№</th>
                      <th>Махсулот</th>
                      <th>Сони</th>
                      <th>Умумий сумма</th>

                    </tr>
                  </thead>
                  <tbody>
                    {% for i in data %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="/series/{{i.product.name_uz}}/{{i.diller.id}}">{{ i.product.name_uz }}</a></td>
                        <td><a href="/series/{{i.product.name_uz}}/{{i.diller.id}}">{{ i.count }} шт</a></td>
                        <td><a href="/series/{{i.product.name_uz}}/{{i.diller.id}}"><b>{%  widthratio i.product.price 1 i.count %}</b></a></td>
                      </tr>
                    {% endfor %}
                  </tbody>
                  <tfoot>
                    <tr>  
                      <td></td>
                      <td></td>
                      <td></td>
                      <td>{{total}}</td>
                    </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
    </div>
</section>
{% endblock %}

templates/dashboard/sold/form.html
{% extends 'dashboard/base.html' %} {% load static %} {% block content %}
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Сотилаган Махсулот Қўшиш</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item">
            <a href="{% url 'home' %}">Асосий</a>
          </li>
          <li class="breadcrumb-item active">Сотилаган Махсулот Қўшиш</li>
        </ol>
      </div>
    </div>
  </div>
  <!-- /.container-fluid -->
</section>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="">
          <form method="post"  enctype="multipart/form-data">
            {% csrf_token %}

            <div class="row">
              <div class="col-6">
                <div class="form-group">
                  <label>Диллер</label><br />
                  {{form.diller}}
                  
                </div>
              </div>
              <div class="col-6">
                <div class="form-group">
                  <label>Махсулот</label><br />
                  {{form.product}}
                </div>
              </div>
              <div class="col-6">
                <div class="form-group">
                  <label>Сотовчи</label><br />
                  {{form.seller}}
                </div>
              </div>
              <div class="col-6">
                <div class="form-group">
                  <label>Махсулот сони</label><br />
                  <!-- <label>Сериа номер</label><br /> -->
                  <input type="number" class="form-control" id="id_serial2" name="serial2">
                  <!-- <textarea name="serial" id="id_serial" class="form-control" cols="30" rows="10"></textarea> -->
                </div>
              </div>
            </div>
            <div class="ml-3">
              <button id="hello" type="submit" class="btn col-sm-1 btn-info">
                Қўшиш
              </button>
              <a href="{% url 'solds' %}" class="btn col-sm-1 btn-secondary">
                Ортга
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}
{% block javascript %}
<script>
  $(document).ready(function(){
   $('select[name="diller"]').on('change',function(){
       var country_id= $(this).val();
       if (country_id) {
        $.ajax({
           url: "/get_sell/"+country_id,
         type: "GET",
         dataType: "json",
         success: function(data){
           console.log(data);
           $('select[name="seller"]').empty();
           $.each(data,function(key,value){
            console.log(key,value);
               $('select[name="seller"]').append('<option value="'+key+'">'+value+'</option>');

           });
         }
        });
       }else {
            $('select[name="state"]').empty();
      }
  });
    
  });
</script>
<script>
  document.getElementById("hello").on("click", function(){
    document.getElementById("hello").style.display="none";
  })
</script>
{% endblock %}

templates/dashboard/sold/list.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Сериа номерлар</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'home' %}">Асосий</a></li>
          <li class="breadcrumb-item active">Сериа номерлар</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Сериа номерлар</h3>

                <div class="card-tools">
                    <a href="{% url 'sold_create' %}"><div class="btn btn-block btn-success">Қўшиш</div></a>
                </div>
              </div>

              
              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                  <thead>
                    <tr>
                      <th>№</th>
                      <th>Диллер</th>
                      <th>Диллер Вилояти</th>
                      <th>Сотовчи</th>
                      <th>Сотовчи Вилояти</th>
                      <th>Махсулотлар</th>
                      <th>Сони</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for i in baseproduct %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="/diller_sold/{{i.diller.id}}">{{ i.diller.name }}</a></td>
                        <td><a href="/diller_sold/{{i.diller.id}}">{{ i.diller.region.uz_data }}</a></td>
                        <td>{{ i.seller.name }}</td>
                        <td>{{ i.seller.region.uz_data }}</td>
                        <td><a href="/diller_sold/{{i.diller.id}}">Maxsulotlar</a></td>
                        <td>{{ i.count }} шт</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
    </div>
</section>
{% endblock %}

templates/dashboard/sold/series.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Сотилаганлар</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'home' %}">Асосий</a></li>
          <li class="breadcrumb-item active">Сотилаганлар</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Сотилаганлар</h3>
              </div>

              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                  <thead>
                    <tr>
                      <th>№</th>
                      <th>Махсулот</th>
                      <th>Serai Nomer</th>
                      <th>Sana</th>
                      <th>O'chirish</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for i in data %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{i.product.name_uz}}</td>
                        <td><b>{{i.serial_number}}</b></td>
                        <td>{{i.date|date:"d/m/Y H:i"}}</td>
                        <td><a style="color: #dc3545;" href="{% url 'serial_delete' pk=i.id %}">
                          <div><i class="fas fa-trash-alt"></i></div></a></td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
    </div>
</section>
{% endblock %}