mysite/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_panel.urls')),
    path('', include('sale.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sale/urls.py
from django.urls import path
from sale.views import cash_orders, promocode_requests_accept, promocode_requests_reject, promocodes_create, sale_diller_delete, sale_diller_detail, sale_dillers_create, update_cash_order, sale_seller, update_sale_seller, wait_cashback, accept_cashback, reject_cashback, update_cashback, sale_statistics
from sale.views import promocodes, promocodes_create_xlsx, promocodes_edit, promocodes_delete
from sale.views import cars, cars_create, cars_edit, cars_delete, promocodes_check, give_to_diller
from sale.views import sale_seller_edit
from sale.views import (
    promocode_requests,
    promocode_requests_edit,
    # promocode_requests_accept,
    # promocode_requests_reject
)
from sale.views import (
    sale_seller2,
    sale_seller2_edit,
    update_sale_seller2
)

from sale.views import sale_dillers


urlpatterns = [
    path('cash/orders', cash_orders, name="cash_orders"),
    path('cash/orders/update/<int:pk>/<int:state>',
         update_cash_order, name="update_cash_orders"),
    path('sale/seller', sale_seller, name="sale_seller"),
    path('sale/seller/<int:pk>', sale_seller_edit, name="seller_edit"),
    path('sale/seller/update/<int:pk>/<int:state>',
         update_sale_seller, name="update_sale_seller"),


    path('cashback/wait', wait_cashback, name="wait_cashback"),
    path('cashback/accept', accept_cashback, name="accept_cashback"),
    path('cashback/reject', reject_cashback, name="reject_cashback"),
    path('cashback/update/<int:pk>/<int:state>',
         update_cashback, name="update_cashback"),

    path('sale/statistics/<int:pk>', sale_statistics, name="statistics"),



    path('promocodes/', promocodes, name="promocodes"),
    path('promocodes/<int:pk>', promocodes_edit, name="promocodes-edit"),
    path('promocodes/delete/<int:pk>',
         promocodes_delete, name="promocodes-delete"),
    path('promocodes/create', promocodes_create, name="promocode-create"),
    path('promocodes/create_xlsx', promocodes_create_xlsx,
         name="promocode-create-xlsx"),
    path('promocodes/check/<str:seria>',
         promocodes_check, name="promocode-check"),
    path('promocodes/give_to_diller', give_to_diller,
         name="promocode-give_to_diller"),



    path('cars/', cars, name="cars"),
    path('cars/<int:pk>', cars_edit, name="cars-edit"),
    path('cars/delete/<int:pk>', cars_delete, name="cars-delete"),
    path('cars/create', cars_create, name="cars-create"),




    path('cars/create', cars_create, name="cars-create"),




    path('promocode_requests/', promocode_requests, name="promocode-requests"),
    path('promocode_requests/<int:pk>', promocode_requests_edit,
         name="promocode-request-edit"),
    path('promocode_requests/<int:pk>', promocode_requests_edit,
         name="promocode-request-delete"),

    path('promocode_requests/accept', promocode_requests,
         name="promocode-request-accept"),
    path('promocode_requests/<int:pk>/accept',
         promocode_requests_accept, name="promocode-request-accept"),
    path('promocode_requests/<int:pk>/reject',
         promocode_requests_reject, name="promocode-request-reject"),





    path('sale_dillers/', sale_dillers, name="sale_dillers"),
    path('sale_dillers/create', sale_dillers_create, name="sale_dillers_create"),
    path('sale_dillers/<int:pk>/', sale_diller_detail, name="sale_diller_detail"),
    path('sale_dillers/<int:pk>/delete',
         sale_diller_delete, name="sale_diller_delete"),





    path('sale/seller2', sale_seller2, name="sale_seller2"),
    path('sale/seller2/<int:pk>', sale_seller2_edit, name="seller_edit2"),
    path('sale/seller2/update/<int:pk>/<int:state>',
         update_sale_seller2, name="update_sale_seller2"),


]

sale/models.py
from typing import TYPE_CHECKING
from django.db import models
from admin_panel.models import District
from seller.models import Regions

from django.utils import timezone





class SaleDiller(models.Model):
    name:str = models.CharField(max_length=100)
    number:str = models.CharField(max_length=100)
    region: Regions = models.ForeignKey(Regions, on_delete=models.SET_NULL, null=True)
    district: District = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)


    promocodes: models.QuerySet["PromoCode"]



    def got_promos(self):
        return self.promocodes.count()

    def used_promos(self):
        return self.promocodes.filter(status=3).count()





class SaleSeller(models.Model):

    WAITING = 1
    CANCELED = -1
    ACCEPT = 2
    chat_id = models.BigIntegerField()
    language = models.CharField(max_length=2, null=True)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=20, null=True)
    region = models.ForeignKey(Regions, on_delete=models.SET_NULL, null=True)
    state = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    account = models.BigIntegerField(default=0)



    ################################
    #          KOMILJONOV          #
    ################################


    diller: "SaleDiller | None" = models.ForeignKey(SaleDiller,on_delete=models.SET_NULL, null=True,blank=True,related_name="sale_sellers")

    last_promocode: "PromoCode" = models.ForeignKey("PromoCode", on_delete=models.SET_NULL,null=True,blank=True)


    gifts: models.QuerySet["UserGift"]
    promocodes: models.QuerySet["PromoCode"]


    ################################
    #        KOMILJONOV END        #
    ################################
    def __str__(self):
        return self.name or ""

    def set_language(self, language):
        self.language = language
        self.save()

    def set_name(self, name):
        self.name = name
        self.save()

    def set_phone(self, phone):
        self.phone = phone
        self.save()

    def set_region(self, region):
        self.region = region
        self.state = self.WAITING
        self.save()

    @property
    def total_sum(self):
        order = Cashback.objects.exclude(state=3).filter(seria__seller=self)
        price = 0
        for i in order:
            price+= i.seria.cashback
        return price

    @property
    def payed_sum(self):
        order = CashOrder.objects.exclude(state=3).filter(seller=self)
        price = 0
        for i in order:
            price+= i.price
        return price
    @property
    def waiting_sum(self):
        cashback = Cashback.objects.filter(seria__seller=self, state=1)
        cashback_price = 0
        for i in cashback:
            cashback_price+= i.seria.cashback
        return cashback_price





    def gifts_text(self, breaker="&nbsp;<br>"):
        gifts_text = ""

        gifts = self.gifts.all()

        for gift in gifts:
            t = ""
            c_count = {}
            for c in gift.car.name:
                i = c_count.get(c,0) + 1
                promo = gift.promocodes.filter(letter__iexact=c, order=i).first()
                if promo:
                    t += promo.letter
                else:
                    t += "*"

                c_count[c] = i

            gifts_text += t + breaker

        return gifts_text.capitalize()




class SaleSeller2(SaleSeller):
    pass



class Card(models.Model):
    seller = models.ForeignKey(SaleSeller, on_delete=models.CASCADE, null=True)
    holder_name = models.CharField(max_length=200)
    card_number = models.CharField(max_length=16)
    created_at = models.DateTimeField(auto_now_add=True)


class SerialNumbers(models.Model):
    code = models.CharField(max_length=200)
    cashback = models.IntegerField()
    is_used = models.BooleanField(default=False)
    seller = models.ForeignKey(SaleSeller, on_delete=models.SET_NULL, null=True, blank=True)
    used_time = models.DateTimeField(null=True, blank=True)
    # def __str__(self):
    #     return f"{self.code} | {self.is_used}"

class CashOrder(models.Model):
    WAITING = 1
    ACCEPTED = 2
    CANCELLED = -1

    seller = models.ForeignKey(SaleSeller, on_delete=models.CASCADE)
    price = models.IntegerField()
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    state = models.SmallIntegerField(default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.seller.name} | {self.state}"


class Cashback(models.Model):
    WAITING = 1
    ACCEPTED = 2
    REJECTED = 3
    photo = models.ImageField(upload_to="cashback/")
    seria = models.ForeignKey(SerialNumbers, on_delete=models.CASCADE, related_name="serialnumber")
    state = models.SmallIntegerField(default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.seria.code} | {self.seria.seller.name} | {self.state}"











################################
#          KOMILJONOV          #
################################


class Car(models.Model):
    name = models.CharField(max_length=255)
    name_ru = models.CharField(max_length=255)


    promocodes: models.QuerySet["PromoCode"]


    def __str__(self) -> str:
        return self.name





# class PromoCode(models.Model):
#     diller: "Diller" = models.ForeignKey("diller.Diller",on_delete=models.SET_NULL,null=True,blank=True)

#     car:Car = models.ForeignKey(Car, on_delete=models.SET_NULL,null=True,blank=True)

#     order = models.IntegerField(default=1)

#     seria = models.CharField(max_length=255)
#     letter = models.CharField(max_length=255)

#     code = models.IntegerField()



class UserGift(models.Model):
    user = models.ForeignKey(SaleSeller2,on_delete=models.CASCADE,related_name="gifts")
    car = models.ForeignKey(Car,on_delete=models.CASCADE)



    promocodes: models.QuerySet["PromoCode"]


class PromoCode(models.Model):
    diller:"SaleDiller" = models.ForeignKey(SaleDiller, on_delete=models.SET_NULL, null=True, blank=True,related_name="promocodes")
    car = models.ForeignKey(Car, on_delete=models.SET_NULL, null=True, blank=True,related_name="promocodes")
    order = models.IntegerField(default=1)
    seria = models.CharField(max_length=255, unique=True)  # Unique individually
    letter = models.CharField(max_length=255)
    code = models.IntegerField(unique=True)  # Unique individually



    status = models.IntegerField(
        choices=[
            (1, "Waiting"),
            (2, "Not used"),
            (3, "Used"),
        ],
        default=1
    )

    seller = models.ForeignKey(SaleSeller2, on_delete=models.SET_NULL,null=True,blank=True,related_name="promocodes")
    image = models.ImageField(upload_to="promocode_images",null=True,blank=True)


    gift = models.ForeignKey(UserGift,on_delete=models.SET_NULL,null=True,blank=True,related_name="promocodes")


    created_at = models.DateTimeField(auto_now_add=True)

    got_at = models.DateTimeField(null=True,blank=True)


    def give_promo(self, request:"PromocodeRequest", db_user:"SaleSeller2"):

        promo = request.promo
        car = promo.car

        gifts = db_user.gifts.filter(car=car)

        for gift in gifts:
            c_count = {}
            for c in gift.car.name.lower():
                i = c_count.get(c,0) + 1

                if c == promo.letter:

                    p = gift.promocodes.filter(letter__iexact=c, order=promo.order).first()
                    if not p:
                        print("Not Found")
                        promo.gift = gift
                        promo.got_at = timezone.now()
                        promo.save()
                        return
                c_count[c] = i

        new_gift = UserGift.objects.create(
            user=db_user,
            car=promo.car
        )
        print("Created")

        promo.gift = new_gift
        promo.save()


    class Meta:
        unique_together = (('car', 'seria', 'letter', 'code'),)  # Unique together

        ordering = ["car", "letter","order"]

    def __str__(self):
        return f"{self.car.name} - {self.letter} - {self.seria} - {self.code}"



    # def gifts_text_seller(self, breaker="<br>"):
    #     gifts_text = ""



    #     # promos = self.seller.promocodes.order_by("got_at").all()



    #     gifts = self.seller.gifts.all()


    #     for gift in gifts:
    #         t = ""
    #         c_count = {}
    #         for c in gift.car.name:
    #             i = c_count.get(c,0) + 1
    #             print(c,i,self.got_at)
                
    #             promo = gift.promocodes.filter(letter__iexact=c, order=i,got_at__lte=self.got_at).first()
                
    #             if promo:
    #                 t += promo.letter
    #             else:
    #                 t += "*"

    #             c_count[c] = i

    #         if any([c != "*" for c in t]):
    #             gifts_text += t + breaker

    #     return gifts_text
    
    
    def gifts_text_seller(self, breaker: str = "<br>") -> str:
        gifts_text = ""
        gifts = self.seller.gifts.all()

        for gift in gifts:
            t = ""
            c_count = {}
            for c in gift.car.name:
                i = c_count.get(c, 0) + 1

                if self.got_at is not None:
                    promo = gift.promocodes.filter(letter__iexact=c, order=i, got_at__lte=self.got_at).first()
                else:
                    promo = gift.promocodes.filter(letter__iexact=c, order=i).first()

                if promo:
                    t += promo.letter
                else:
                    t += "*"

                c_count[c] = i

            if any([c != "*" for c in t]):
                gifts_text += t + breaker

        return gifts_text













class PromocodeRequest(models.Model):

seller/models.py
from datetime import datetime
from django.db import models

from admin_panel.models import District, Gifts, Regions, Text,Product

# Create your models here.
class Seller(models.Model):
    id:int
    chat_id:int = models.IntegerField()
    name:str = models.CharField(max_length=100)
    number:str = models.CharField(max_length=100)
    balls:int = models.IntegerField(default=0)
    region: Regions = models.ForeignKey(Regions, on_delete=models.SET_NULL, null=True)
    district: District = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)
    shop:str = models.CharField(max_length=300,null=True,blank=True)
    language:int = models.IntegerField(choices=((0, 'uz'), (1, 'ru')))
    shop_location: dict = models.JSONField(default=dict)
    shop_passport_photo = models.ImageField(upload_to='shop_passport_photo', null=True, blank=True)
    passport_photo = models.ImageField(upload_to='passport_photo', null=True, blank=True)
    dillers = models.ManyToManyField("diller.Diller")
    status:int = models.IntegerField(default=0, choices=(
        (0, "Kutilmoqda"),
        (1, "Qabul qilingan"),
        (2, "Rad etilgan"),
        (3,"Muzlatilgan")
    ))
    
    def text(self, name) -> str:
        text = Text.objects.filter(name=name)
        return (text.first().uz_data if self.language == 0 else text.first().ru_data) if text.exists() else ""
    
    def get_gift(self, gift) -> "OrderGiftSeller":
        return OrderGiftSeller.objects.create(user=self, gift=gift)

    def __str__(self):
        return self.name
    


class OrderGiftSeller(models.Model):
    user: Seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    gift= models.ForeignKey("admin_panel.Gifts", on_delete=models.CASCADE)
    date: datetime = models.DateTimeField(auto_now_add=True)
    status:int = models.IntegerField(choices=((0,"Kutilmoqda"),(1,"Qabul qilingan"),(3,"Rad etilgan")),default=0)


class Cvitation(models.Model):
    seller: Seller = models.ForeignKey(Seller, on_delete=models.SET_NULL, null=True)
    serial:str = models.CharField(max_length=100)
    img = models.ImageField(upload_to='cvitations/')
    date:datetime = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(default=0,choices=((0,"Kutilmoqda"),(1,"Qabul qilingan"),(3,"Rad etilgan")))
    current_ball = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL,null=True,blank=True)

    def __str__(self):
        if self.seller:
            return f"{self.seller.name} | {self.serial}"
        else:
            return f"None | {self.serial}"

templates/dashboard/base.html
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ELITE</title>
  <script src="https://api-maps.yandex.ru/2.1/?lang=ru_ru&apikey=*7494e3e7-008f-4e03-bd72-31a4650591f7" type="text/javascript">
  </script>
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dashboard/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
  {% block style %}{% endblock %}

</head>
<body class="hold-transition sidebar-mini layout-fixed">


  <div class="wrapper" style="min-height: 1342.88px;">


    {% include 'dashboard/navbar.html' %}

    <div class="content-wrapper" style="min-height: 1342.88px;">
      {% block content %}{% endblock %}
      <aside class="control-sidebar control-sidebar-dark">

        <!-- Control sidebar content goes here -->
      </aside>
    </div>
  </div>

<!-- jQuery -->
<script src="{% static 'dashboard/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'dashboard/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'dashboard/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dashboard/js/adminlte.js' %}"></script>



{% block javascript %}{% endblock %}
</body>
</html>

templates/dashboard/diller.html
{% extends 'dashboard/base.html' %} {% load static %} {% load currency %} {% block style %}
<link
  rel="stylesheet"
  href="{% static 'dashboard/plugins/fontawesome-free/css/all.min.css' %}"
/>
<!-- DataTables -->
<link
  rel="stylesheet"
  href="{% static 'dashboard/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}"
/>
<link
  rel="stylesheet"
  href="{% static 'dashboard/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}"
/>
<link
  rel="stylesheet"
  href="{% static 'dashboard/plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}"
/>
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dashboard/css/adminlte.min.css' %}" />
{% endblock %} {% block content %}
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Диллерлар</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'home' %}">Асосий</a></li>
          <li class="breadcrumb-item active">Диллерлар</li>
        </ol>
      </div>
    </div>
  </div>
  <!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <!-- /.card -->

        <div class="card p-2">
          <div class="card-header">
            <h3 class="card-title"></h3>

            <div class="card-tools">
              <a href="{% url 'diller_create' %}">
                <div class="btn btn-block btn-success">Қўшиш</div>
              </a>
            </div>
          </div>
          <div class="card-body table-responsive p-0">
            <table id="example1" class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>№</th>
                  <th>ФИО</th>
                  <th>Телефон</th>
                  <th>Вилоят</th>
                  <th>Туман</th>
                  <th>Тил</th>
                  <th>Балл</th>
                  <!-- <th>Stikerlar berilgan</th> -->
                  <!-- <th>Stikerlar qabul qilindi</th> -->

                  <th>Ҳолати</th>
                  <th>Тасдиқлаш</th>
                  <th>Рад этиш</th>
                  <th>Ўчириш</th>
                </tr>
              </thead>
              <tbody>
                {% for i in dillers %}
                <tr>
                  <td>{{forloop.counter}}</td>
                  <td><a href="{% url 'diller_detail' pk=i.id %}">{{i.name}}</td></td>
                  <td><a href="tel:{{i.number}}">{{i.number}}</a></td>

                  <td>{{i.region.ru_data}}</td>
                  <td>{{i.district.ru_data}}</td>
                  <td>{{i.get_language_display}}</td>
                  <td>{% money i.balls %}</td>
                  <!-- <td>{{ i.got_promos }}</td> -->
                  <!-- <td>{{ i.used_promos }}</td> -->
                  {% if i.status == 0 %}
                  <td><span class="badge badge-warning">{{i.get_status_display}}</span></td>
                  <td>
                    <a href="{% url 'diller_update' pk=i.pk status=1 %}" class="btn btn-xs btn-success"
                      ><i class="p-1 fas fa-check-circle"></i
                    ></a>
                  </td>
                  <td>
                    <a href="{% url 'diller_update' pk=i.pk status=2 %}" class="btn btn-xs btn-danger"
                      ><i class="p-1 fas fa-times-circle"></i
                    ></a>
                  </td>
                  <td>
                    <a class="btn btn-xs btn-secondary disabled"
                      ><i class="p-1 far fa-trash-alt"></i></a>
                  </td>
                  {% elif i.status == 1 %}
                  <td><span class="badge badge-success">{{i.get_status_display}}</span></td>
                  <td>
                    <a  class="btn btn-xs btn-secondary disabled"
                      ><i class="p-1 fas fa-check-circle"></i
                    ></a>
                  </td>
                  <td>
                    <a class="btn btn-xs btn-secondary disabled"
                      ><i class="p-1 fas fa-times-circle"></i
                    ></a>
                  </td>
                  <td>
                    <a href="{% url 'diller_delete' i.pk %}" class="btn btn-xs btn-danger"
                      ><i class="p-1 far fa-trash-alt"></i></a>
                  </td>
                  {% else %}
                  <td><span class="badge badge-danger">{{i.get_status_display}}</span></td>
                  <td>
                    <a class="btn btn-xs btn-secondary disabled"
                      ><i class="p-1 fas fa-check-circle"></i
                    ></a>
                  </td>
                  <td>
                    <a class="btn btn-xs btn-secondary disabled"
                      ><i class="p-1 fas fa-times-circle"></i
                    ></a>
                  </td>
                  <td>
                    <a href="{% url 'diller_delete' i.pk %}" class="btn btn-xs btn-danger"
                      ><i class="p-1 far fa-trash-alt"></i></a>
                  </td>
                  {% endif %}

                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Control Sidebar -->
<!-- <aside class="control-sidebar control-sidebar-dark"> -->
<!-- Control sidebar content goes here -->
<!-- </aside> -->
<!-- /.control-sidebar -->
<!-- ./wrapper -->
{% endblock %} {% block javascript %}
<script src="{% static 'dashboard/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<script src="/static/dashboard/js/adminlte.min.js"></script>
<script src="/static/dashboard/js/demo.js"></script>
<script>
  $(function () {
    $("#example1")
      .DataTable({
        responsive: true,
        lengthChange: false,
        autoWidth: false,
        buttons: ["copy", "csv", "excel", "pdf", "print"],
      })
      .buttons()
      .container()
      .appendTo("#example1_wrapper .col-md-6:eq(0)");

    //   $("#example2").DataTable({
    //   paging: true,
    //   lengthChange: false,
    //   searching: false,
    //   ordering: true,
    //   info: true,
    //   autoWidth: false,
    //   responsive: true,
    // });

  });
  // setInterval(() => {
  //   location.reload();
  // }, 30000);
</script>
{% endblock %}

templates/dashboard/form.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Order List</h1>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
            <div class="card card-primary">

              <form method="post" >
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label >Order status</label>
                      {{form.status}}
                  </div>
                </div>
                <div class="card-body">
                  <div class="form-group">
                    <label >Order status</label>
                      {{form.total_price}}
                  </div>
                </div>
<!--                <div class="card-body">-->
<!--                  <div class="form-group">-->
<!--                    <label >Order total_price</label>-->
<!--                      {{form.total_price}}-->
<!--                  </div>-->
<!--                </div>-->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>

          </div>
        </div>
    </div>
</section>
{% endblock %}